const juego = {
  romanticos: {
    preguntas: [
      "¿Qué fue lo primero que sentiste por mí?",
      "¿Cuál ha sido tu momento favorito conmigo hasta ahora?",
      "¿Qué es lo que más te gusta de nuestra relación?",
      "¿Cómo te sientes cuando estamos separados por mucho tiempo?",
      "¿Qué es lo que más te hace sonreír de mí?",
      "¿Qué es lo que más te gusta de mi forma de amar?",
      "¿Hay algo que siempre hayas querido decirme y no lo hayas hecho?",
      "¿Qué significa para ti 'amor verdadero'?",
      "¿Qué es lo que más valoras en nuestra relación?",
      "¿Cuál es la cualidad mía que más admiras?",
      "¿Cuál fue tu primera impresión de mí?",
      "¿Cuál ha sido nuestra cita más memorable?",
      "¿Qué recuerdo nuestro te hace sonreír siempre?",
      "¿Cuál ha sido el momento más romántico que hemos vivido?",
      "¿Qué gesto mío te hizo sentir más amado/a?",
      "¿Cómo te imaginas nuestra vida juntos dentro de cinco años?",
      "¿Qué lugares sueñas con visitar conmigo?",
      "¿Qué metas te gustaría que alcanzáramos juntos?",
      "¿Te gustaría casarte y tener hijos conmigo algún día?",
      "¿Cómo te gustaría celebrar nuestro aniversario ideal?",
      "¿Cuál es tu forma favorita de recibir cariño de mí?",
      "¿Qué tipo de abrazos te hacen sentir más seguro/a?",
      "¿Qué te gustaría que hiciéramos más a menudo como pareja?",
      "¿Cuál es la forma de demostrar amor que más te gusta?",
      "¿Te gusta más que te sorprendan con palabras o con acciones?",
      "¿Cuál es tu fantasía romántica conmigo?",
      "¿Qué canción te recuerda a mí?",
      "Si pudiéramos pasar un día entero solo los dos, ¿qué harías?",
      "¿Cuál ha sido el beso más memorable que te he dado?",
      "¿Qué parte de mi cuerpo te gusta abrazar más?",
      "¿Qué crees que nos hace una pareja especial?",
      "¿Qué piensas cuando decimos 'te amo'?",
      "¿Qué es lo que más te sorprende de nuestra relación?",
      "¿Cómo describirías nuestro amor en una palabra?",
      "¿Qué pequeños hábitos míos te hacen sentir amado/a?",
      "¿Qué cosas te gusta compartir conmigo que no compartes con nadie más?",
      "¿Cómo te siento apoyado/a en momentos difíciles?",
      "¿Qué te hace confiar más en mí?",
      "¿Qué sueño o miedo tuyo te gustaría que yo entendiera mejor?",
      "¿Cómo te gustaría que te consuele cuando estás triste?",
      "¿Crees que el amor puede cambiar a las personas?",
      "¿Qué significa para ti la palabra 'compromiso'?",
      "¿Cuál es tu definición de felicidad en pareja?",
      "¿Qué cualidades buscas en una pareja ideal?",
      "¿Cómo crees que nos complementamos como pareja?",
      "¿Cuál es la cosa más tonta que has hecho por mí?",
      "¿Qué apodo cariñoso te gusta que te ponga?",
      "¿Qué te gustaría que hiciéramos para reírnos juntos?",
      "Si tuvieras que describir nuestro amor como un color, ¿cuál sería?",
      "¿Qué pequeños detalles míos te hacen sentir más amado/a?"

    ],
    retos: [
      "Dile algo bonito al oído sin que nadie lo escuche",
      "Dale un abrazo durante 1 minuto sin soltarlo",
      "Escríbele una nota de amor y entrégasela ahora mismo",
      "Mírale a los ojos durante 30 segundos sin hablar",
      "Dale un masaje en las manos durante 2 minutos",
      "Hazle un cumplido creativo y divertido",
      "Bésale en la frente y dile lo mucho que lo/la amas",
      "Hazle un dibujo romántico y regálaselo",
      "Envía un mensaje romántico sin usar palabras",
      "Susurra tu canción favorita para él/ella",
      "Prepara un pequeño regalo sorpresa con lo que tengas a la mano",
      "Dale un abrazo por la espalda inesperadamente",
      "Hazle una declaración de amor improvisada",
      "Escríbele una lista de 5 cosas que amas de él/ella",
      "Dibuja un corazón en su mano y dile algo lindo",
      "Hazle un pequeño baile solo para él/ella",
      "Canta su canción favorita aunque no sepas la letra",
      "Escribe un poema corto y léelo en voz alta",
      "Mira su foto y dile qué te hace feliz de él/ella",
      "Hazle un gesto romántico sin palabras",
      "Déjale un mensaje romántico en un lugar inesperado",
      "Abraza su cintura y dile lo especial que es para ti",
      "Dile un secreto romántico que nunca le hayas dicho",
      "Prepara una cita improvisada en casa",
      "Envía un emoji romántico cada hora por 3 horas",
      "Mímalo/a durante 5 minutos sin decir palabras",
      "Cógelo/a de la mano y caminen juntos sin hablar",
      "Hazle un cumplido sobre su personalidad",
      "Regálale un post-it con un mensaje romántico",
      "Canta una canción inventada sobre los dos",
      "Dibuja algo que te recuerde a él/ella",
      "Escríbele un mensaje de buenas noches muy romántico",
      "Dile 3 cosas que te hacen sentir especial cuando estás con él/ella",
      "Hazle un masaje rápido en los hombros",
      "Tóquense las manos mientras se miran a los ojos",
      "Dile algo lindo usando solo gestos",
      "Haz un pequeño regalo con algo que tengas a la mano",
      "Susurra un cumplido que nunca le hayas dicho",
      "Escríbele un mini cuento romántico",
      "Dibuja un corazón en su espalda y explícale qué significa",
      "Dale un beso inesperado en la mejilla",
      "Hazle un cumplido sobre su sonrisa",
      "Abraza su cuello y dile algo que te guste de él/ella",
      "Haz un pequeño ritual romántico, como brindar con vasos imaginarios",
      "Dile tu frase favorita sobre el amor y cómo aplica para ustedes",
      "Hazle un mini dibujo en la palma de su mano",
      "Bésale las manos y dile algo bonito",
      "Hazle un juego de miradas y sonrisas durante 1 minuto",
      "Dile 3 cosas que nunca le has dicho y que amas de él/ella",
      "Prepara un mini picnic en cualquier lugar",
      "Hazle un gesto romántico con lo que tengas a la mano",
      "Cógelo/a de la mano y recuérdale un momento especial que hayan vivido",
      "Hazle un cumplido sobre algo que solo tú notas en él/ella"
    ]
  },

  eroticos: {
    preguntas: [
      "¿Cuál es tu fantasía sexual más secreta?",
      "¿Qué parte de mi cuerpo te atrae más?",
      "¿Qué tipo de caricias te excitan más?",
      "¿Te gusta que te hablen sucio o suave durante el sexo?",
      "¿Cuál ha sido tu experiencia sexual más intensa?",
      "¿Tienes alguna fantasía que quieras cumplir conmigo?",
      "¿Qué ropa o lencería te gustaría que usara para ti?",
      "¿Prefieres tomar la iniciativa o que yo lo haga?",
      "¿Te gustan los besos largos y apasionados o rápidos y ardientes?",
      "¿Cuál es tu lugar favorito para que te toque?",
      "¿Te excita más la mente o el cuerpo?",
      "¿Qué tipo de caricias disfrutas en la espalda o cuello?",
      "¿Te gusta jugar con la temperatura durante los juegos íntimos (hielo, calor)?",
      "¿Cuál es tu postura favorita en la intimidad?",
      "¿Qué te gustaría que exploráramos juntos en la cama?",
      "¿Te gusta que te susurre cosas atrevidas al oído?",
      "¿Prefieres luz tenue o oscuridad total?",
      "¿Cuál es tu juguete sexual favorito o que te gustaría probar?",
      "¿Te gustan los juegos de roles o disfraces?",
      "¿Te excita más la anticipación o la acción inmediata?",
      "¿Cuál es tu zona erógena más sensible?",
      "¿Te gustaría experimentar algo nuevo conmigo?",
      "¿Qué palabra o gesto te vuelve loco/a de deseo?",
      "¿Prefieres caricias suaves o más intensas?",
      "¿Cuál es tu recuerdo sexual más excitante conmigo?",
      "¿Te gusta que te den órdenes o que tú las des?",
      "¿Te excitan los besos en el cuello y orejas?",
      "¿Qué tipo de besos te gusta más: suaves, mordidos o apasionados?",
      "¿Qué fantasía quieres que haga realidad esta semana?",
      "¿Te gusta que te toquen mientras hablamos?",
      "¿Cuál es tu límite que te gustaría explorar poco a poco?",
      "¿Qué parte de mi cuerpo te provoca más deseo?",
      "¿Prefieres juegos lentos y sensuales o rápidos y ardientes?",
      "¿Te gusta la intimidad en lugares públicos o solo privados?",
      "¿Qué accesorios o ropa te gustaría incorporar?",
      "¿Prefieres que yo lleve el control o tú?",
      "¿Te gustan los masajes con final erótico?",
      "¿Qué palabra o frase despierta tu excitación instantánea?",
      "¿Te gustaría que grabemos algún momento íntimo?",
      "¿Qué posición quieres intentar que aún no lo hemos hecho?",
      "¿Te excita el juego de miradas durante el coqueteo?",
      "¿Te gusta hablar de fantasías mientras nos tocamos?",
      "¿Qué gesto mío te vuelve loco/a de deseo?",
      "¿Te gustan los juegos de temperatura con velas o hielo?",
      "¿Qué parte de tu cuerpo quieres que explore más?",
      "¿Prefieres juegos eróticos largos o rápidos y apasionados?",
      "¿Qué tipo de beso te vuelve más loco/a: mordido o suave?",
      "¿Qué fantasía quieres que probemos en un futuro cercano?",
      "¿Te excita que te sorprenda con caricias inesperadas?",
      "¿Cuál es la zona más prohibida que te gustaría explorar conmigo?",
      "¿Te gustaría probar sexo sensorial (con vendas o música)?",
      "¿Qué frase sexy quieres que te diga mientras te toco?",
      "¿Te gusta recibir besos y caricias mientras me hablas sucio?"

    ],
    retos: [
      "Dame un beso apasionado mientras me recorres el cuerpo con tus manos",
      "Hazme un masaje íntimo con movimientos lentos y provocativos",
      "Susúrrame tu fantasía sexual más atrevida al oído",
      "Desnúdame parcialmente mientras me miras fijamente",
      "Hazme un striptease completo solo para mí",
      "Bésame en zonas erógenas y descríbeme lo que sientes",
      "Tócame con intensidad en mis partes más sensibles",
      "Usa tus labios y lengua para explorar mi cuerpo lentamente",
      "Hazme un juego de anticipación: toca pero no dejes que toque aún",
      "Explora mi cuello y orejas con besos húmedos",
      "Hazme gemir solo con tus caricias",
      "Dame un beso en la zona más íntima que me haga estremecer",
      "Cógeme y recorre mi cuerpo con besos intensos",
      "Hazme un masaje sensual en los muslos internos",
      "Susúrrame palabras sucias mientras me tocas",
      "Hazme un toque erótico usando solo tus manos y labios",
      "Bésame mientras me exploras con tus manos por todo el cuerpo",
      "Haz un mini juego de roles sexual por 5 minutos",
      "Hazme un toque intenso y apasionado mientras me miras a los ojos",
      "Explora mis zonas más sensibles con caricias prolongadas",
      "Hazme un beso lento recorriendo desde el cuello hasta el pecho",
      "Tócame y hazme gemir suavemente",
      "Bésame profundamente mientras acaricias mis zonas íntimas",
      "Hazme un juego de anticipación erótica con vendas y caricias",
      "Susúrrame lo que quieres hacerme mientras me tocas",
      "Explora mi espalda y glúteos con besos y caricias",
      "Dame un beso intenso en el abdomen y sube lentamente",
      "Hazme un mini striptease con movimientos sensuales",
      "Tócame y susúrrame algo que me excite",
      "Hazme gemir solo con tus labios recorriendo mi cuerpo",
      "Bésame en lugares secretos mientras me susurras palabras atrevidas",
      "Hazme un masaje erótico prolongado en muslos y cadera",
      "Explora mis zonas íntimas con caricias lentas y provocativas",
      "Bésame lentamente mientras recorre tus manos por todo mi cuerpo",
      "Hazme un toque intenso y provocador con tus labios",
      "Susúrrame palabras sucias mientras me abrazas",
      "Hazme un juego de anticipación y negación erótica",
      "Explora mis labios y cuello con besos húmedos y largos",
      "Bésame apasionadamente mientras me acaricias con firmeza",
      "Hazme gemir mientras exploras mi torso y muslos con besos",
      "Tócame suavemente mientras me dices lo que quieres hacerme",
      "Hazme un mini masaje erótico en zonas prohibidas",
      "Bésame en la cintura y glúteos lentamente",
      "Susúrrame tu deseo más atrevido mientras me tocas",
      "Explora mi espalda y cadera con besos lentos y sensuales",
      "Hazme gemir solo con tus caricias y besos íntimos",
      "Bésame en lugares íntimos mientras me miras fijamente",
      "Haz un juego de anticipación: acaricia pero no dejes que toque aún",
      "Tócame apasionadamente mientras me susurras palabras eróticas",
      "Explora mi cuerpo con besos y caricias intensas",
      "Bésame y hazme gemir mientras recorres mi cuerpo lentamente",
      "Haz un mini striptease y acércate a mí de manera provocativa"
    ]
  },

  casuales: {
    preguntas: [
      "¿Cuál es tu comida favorita?",
      "¿Prefieres el cine o ver series en casa?",
      "¿Cuál es tu lugar ideal para ir de vacaciones?",
      "¿Tienes algún hobby que disfrutes mucho?",
      "¿Cuál es tu bebida favorita?",
      "¿Prefieres playa o montaña?",
      "¿Eres más de madrugar o trasnochar?",
      "¿Cuál es tu color favorito?",
      "¿Tienes alguna serie o película favorita?",
      "¿Te gusta cocinar o prefieres comer fuera?",
      "¿Cuál es tu animal favorito?",
      "¿Prefieres perros o gatos?",
      "¿Cuál es tu estación del año favorita?",
      "¿Tienes algún talento oculto?",
      "¿Te gustan los deportes? ¿Cuáles?",
      "¿Prefieres leer un libro o escuchar música?",
      "¿Cuál es tu canción favorita del momento?",
      "¿Prefieres dulces o salados?",
      "¿Cuál es tu lugar soñado para vivir?",
      "¿Tienes algún recuerdo de la infancia que te haga sonreír?",
      "¿Prefieres fiestas grandes o reuniones pequeñas?",
      "¿Cuál es tu película favorita de todos los tiempos?",
      "¿Te gusta viajar? ¿A dónde te gustaría ir?",
      "¿Cuál es tu serie de televisión favorita?",
      "¿Prefieres café o té?",
      "¿Te gustan los videojuegos? ¿Cuál es tu favorito?",
      "¿Cuál es tu comida rápida favorita?",
      "¿Prefieres cine de terror o comedia?",
      "¿Tienes algún libro que releas con frecuencia?",
      "¿Cuál es tu postre favorito?",
      "¿Prefieres invierno o verano?",
      "¿Te gustan los parques de diversiones?",
      "¿Cuál es tu red social favorita?",
      "¿Prefieres llamadas o mensajes de texto?",
      "¿Tienes algún talento artístico?",
      "¿Cuál es tu serie animada favorita?",
      "¿Prefieres películas o series?",
      "¿Cuál es tu sabor de helado favorito?",
      "¿Tienes algún lugar favorito en tu ciudad?",
      "¿Prefieres salir a caminar o quedarte en casa?",
      "¿Cuál es tu comida internacional favorita?",
      "¿Te gusta más el día o la noche?",
      "¿Prefieres música en vivo o grabada?",
      "¿Tienes algún ritual diario que disfrutes?",
      "¿Cuál es tu bebida alcohólica favorita, si tomas?",
      "¿Prefieres leer ficción o no ficción?",
      "¿Cuál es tu comida reconfortante favorita?",
      "¿Tienes alguna app que uses todo el tiempo?",
      "¿Prefieres ver películas solo o acompañado?",
      "¿Cuál es tu lugar favorito para relajarte?",
      "¿Tienes algún lugar que sueñes con visitar algún día?"
    ],
    retos: [
      "Cuenta un chiste que te haga reír",
      "Imita a alguien famoso durante 1 minuto",
      "Haz 10 saltos en el lugar",
      "Baila tu canción favorita por 30 segundos",
      "Haz una mueca graciosa y manténla 10 segundos",
      "Canta una parte de tu canción favorita",
      "Dibuja algo en un papel en 30 segundos",
      "Haz 5 sentadillas mientras cantas",
      "Nombra 5 cosas que te hagan feliz",
      "Cuenta un recuerdo divertido de tu infancia",
      "Haz un reto de trabalenguas",
      "Imita el sonido de un animal que elijan",
      "Haz un dibujo con los ojos cerrados",
      "Describe tu día usando solo gestos",
      "Haz un mini monólogo sobre algo absurdo",
      "Imita tu personaje de película favorito",
      "Cuenta algo embarazoso que te haya pasado",
      "Haz una pose ridícula y manténla 10 segundos",
      "Canta el abecedario al revés",
      "Imita a tu profesor/a favorito/a",
      "Baila sin música durante 20 segundos",
      "Cuenta una mentira divertida y que todos adivinen si es verdad",
      "Haz 10 saltos con giro",
      "Nombra 3 cosas que no te gusten y dramatízalas",
      "Haz un dibujo de tu mascota imaginaria",
      "Canta una canción inventada",
      "Imita a un animal mientras caminas",
      "Haz una mini coreografía con lo que tengas a mano",
      "Haz 5 abdominales mientras dices tu nombre completo",
      "Cuenta un chiste que nunca hayas contado antes",
      "Imita la risa de otra persona",
      "Dibuja tu comida favorita en 30 segundos",
      "Haz una pose de superhéroe",
      "Cuenta una historia inventada en 1 minuto",
      "Haz un sonido de efecto especial y dramatízalo",
      "Nombra 5 películas que te gusten sin mirar el teléfono",
      "Haz un mini espectáculo de magia con algo a mano",
      "Baila como si estuvieras en un concurso de talentos",
      "Imita a un personaje de caricatura",
      "Cuenta algo raro que hayas visto hoy",
      "Haz 10 saltos imitando un animal",
      "Dibuja un autorretrato en 30 segundos",
      "Haz 5 sentadillas mientras cantas tu canción favorita",
      "Imita el sonido de un instrumento musical",
      "Haz una imitación de un famoso y que los demás adivinen",
      "Crea un gesto para saludar inventado",
      "Haz un mini reto de adivinanza",
      "Baila como si nadie te estuviera viendo",
      "Cuenta algo gracioso que te haya pasado en la escuela/trabajo",
      "Haz una pose de yoga graciosa",
      "Imita a tu amigo/a más cercano/a",
      "Canta con voz de robot por 30 segundos",
      "Cuenta 3 cosas curiosas sobre ti que pocos saben"
    ]
  },

  picantes: {
    preguntas: [
      "¿Cuál es tu mayor miedo en la vida?",
      "¿Qué es lo que más valoras en una amistad?",
      "¿Qué significa para ti la felicidad?",
      "¿Qué evento de tu vida te ha cambiado más?",
      "¿Cuál es tu mayor sueño y por qué?",
      "¿Qué es lo más difícil que has tenido que superar?",
      "¿Crees en el destino o en las decisiones que tomamos?",
      "¿Qué significa el amor para ti?",
      "¿Cuál es tu mayor arrepentimiento?",
      "¿Qué crees que te hace verdaderamente feliz?",
      "¿Cuál es tu mayor fortaleza y tu mayor debilidad?",
      "¿Qué es lo que más te inspira en la vida?",
      "Si pudieras cambiar algo de tu pasado, ¿qué sería?",
      "¿Qué significa para ti el éxito?",
      "¿Qué valores consideras más importantes en la vida?",
      "¿Qué te gustaría lograr antes de morir?",
      "¿Cómo manejas los momentos de tristeza?",
      "¿Qué te hace sentir más vulnerable?",
      "¿Cuál es la lección más importante que has aprendido?",
      "¿Qué es lo que más te motiva a seguir adelante?",
      "Si pudieras hablar con tu yo del pasado, ¿qué le dirías?",
      "¿Qué es lo que más aprecias en tu familia?",
      "¿Cuál ha sido tu mayor sacrificio por alguien?",
      "¿Qué significa para ti la libertad?",
      "¿Cuál es tu recuerdo más valioso?",
      "¿Qué opinas sobre la vida después de la muerte?",
      "¿Qué significa para ti la honestidad?",
      "¿Qué te hace sentir más orgulloso/a de ti mismo/a?",
      "¿Qué importancia tienen los sueños en tu vida?",
      "¿Qué cambios te gustaría hacer en tu vida?",
      "¿Cuál ha sido tu experiencia más transformadora?",
      "¿Qué es lo que más temes perder?",
      "Si pudieras dar un consejo a todo el mundo, ¿cuál sería?",
      "¿Qué es lo que más te preocupa del futuro?",
      "¿Qué significa para ti la paz interior?",
      "¿Cuál ha sido la decisión más difícil que has tomado?",
      "¿Qué papel juega la gratitud en tu vida?",
      "Si pudieras pasar un día con alguien del pasado, ¿quién sería?",
      "¿Qué crees que nos hace humanos?",
      "¿Qué importancia tiene la espiritualidad en tu vida?",
      "¿Qué acto de bondad reciente te hizo sentir bien?",
      "¿Qué es lo más valiente que has hecho?",
      "Si pudieras cambiar algo del mundo, ¿qué sería?",
      "¿Qué te hace sentir amado/a?",
      "¿Cuál es tu mayor deseo en este momento?",
      "¿Qué significa para ti el perdón?",
      "¿Qué cosas te hacen sentir verdaderamente vivo/a?",
      "Si pudieras aprender algo instantáneamente, ¿qué sería?",
      "¿Qué te gustaría que recordaran de ti?",
      "¿Cuál es tu mayor desafío emocional actualmente?",
      "¿Qué significa para ti la conexión con otros?",
      "¿Cuál es tu visión de una vida plena y significativa?"
    ],
    retos: [
      "Bésame en un lugar prohibido por 30 segundos",
      "Hazme un mini striptease",
      "Susúrrame tu fantasía más atrevida al oído",
      "Dame un masaje sensual de 5 minutos",
      "Hazme gemir solo con tus manos",
      "Bésame mientras me recorres el cuerpo lentamente",
      "Cógeme de la mano y recorre mi torso con ella",
      "Explora mi cuello y orejas con besos húmedos",
      "Haz un juego de anticipación: toca pero no dejes que toque aún",
      "Dame un beso en una zona íntima",
      "Susúrrame palabras atrevidas mientras me abrazas",
      "Explora mis zonas sensibles con caricias lentas",
      "Haz un mini juego de roles provocativo por 3 minutos",
      "Bésame en la espalda y susúrrame algo excitante",
      "Tócame solo con tus labios y lengua por todo el torso",
      "Hazme un toque erótico mientras me miras a los ojos",
      "Explora mis muslos internos con caricias lentas",
      "Bésame en la cintura y recorre mi cuerpo con tus manos",
      "Haz un mini striptease mientras susurras algo atrevido",
      "Susúrrame tu deseo más intenso mientras me tocas",
      "Bésame en lugares erógenos y hazme gemir",
      "Explora mi espalda y glúteos con besos lentos",
      "Haz un masaje erótico prolongado usando aceite",
      "Bésame mientras alternas caricias suaves e intensas",
      "Susúrrame palabras sucias mientras me acaricias",
      "Explora mi cuerpo con besos húmedos y provocativos",
      "Haz un toque erótico prolongado mientras me miras",
      "Bésame en los muslos y sube lentamente",
      "Hazme gemir con movimientos lentos y provocativos",
      "Susúrrame tu fantasía más atrevida y ejecútala",
      "Explora mis zonas íntimas con caricias sensuales",
      "Bésame profundamente mientras recorro tu cuerpo con mis manos",
      "Haz un mini juego de anticipación erótica",
      "Explora mi torso y cadera con besos húmedos",
      "Hazme gemir mientras tus manos recorren mi cuerpo",
      "Susúrrame algo atrevido mientras me abrazas",
      "Bésame en cada zona erógena lentamente",
      "Tócame con intensidad alternando suavidad y firmeza",
      "Haz un mini striptease provocativo mientras me miras",
      "Explora mis muslos y cadera con besos y caricias",
      "Hazme gemir solo con tus labios y lengua",
      "Susúrrame tu deseo más atrevido mientras me recorres",
      "Bésame en la zona íntima y sube lentamente",
      "Hazme un toque prolongado y excitante",
      "Explora mis zonas sensibles con movimientos lentos",
      "Bésame mientras me susurras palabras eróticas",
      "Haz un mini masaje erótico en las zonas más sensibles",
      "Explora mi espalda y glúteos con caricias y besos",
      "Hazme gemir mientras me recorres con tus labios",
      "Susúrrame palabras provocativas mientras me tocas",
      "Bésame intensamente mientras tus manos exploran mi cuerpo",
      "Haz un juego de anticipación: toca, besa, pero no permitas tocar aún"
    ]
  },

  profundos: {
    preguntas: [
      "¿Cuál ha sido el momento más importante de tu vida?",
      "¿Qué es lo que más valoras en una relación?",
      "¿Cuál ha sido tu mayor aprendizaje hasta ahora?",
      "¿Qué es lo que más temes perder?",
      "¿Qué significa para ti la felicidad?",
      "Si pudieras cambiar una cosa de tu pasado, ¿qué sería?",
      "¿Qué te hace sentir más vivo/a?",
      "¿Cuál es tu mayor sueño en la vida?",
      "¿Qué lecciones has aprendido de tus fracasos?",
      "¿Cuál es tu mayor fortaleza y tu mayor debilidad?",
      "¿Qué significa el amor verdadero para ti?",
      "¿Qué es lo que más aprecias en tus amigos?",
      "Si pudieras hablar con tu yo del pasado, ¿qué le dirías?",
      "¿Qué importancia tiene la familia en tu vida?",
      "¿Cuál ha sido la decisión más difícil que has tomado?",
      "¿Qué valores consideras esenciales en la vida?",
      "Si pudieras cambiar algo en el mundo, ¿qué sería?",
      "¿Qué significa la libertad para ti?",
      "¿Qué te hace sentir más orgulloso/a de ti mismo/a?",
      "¿Cuál ha sido tu mayor sacrificio por alguien más?",
      "¿Qué papel juega la espiritualidad en tu vida?",
      "Si pudieras vivir en cualquier época, ¿cuál elegirías y por qué?",
      "¿Qué significa para ti la honestidad?",
      "¿Cuál ha sido la lección más dura que has aprendido?",
      "¿Qué te hace sentir más vulnerable?",
      "Si pudieras pasar un día con cualquier persona, viva o muerta, ¿quién sería?",
      "¿Qué es lo que más te motiva a seguir adelante?",
      "¿Cuál es tu recuerdo más valioso?",
      "¿Qué importancia tienen los sueños en tu vida?",
      "Si pudieras aprender algo instantáneamente, ¿qué sería?",
      "¿Qué significa para ti la paz interior?",
      "¿Cuál es tu mayor arrepentimiento?",
      "¿Qué cambios te gustaría hacer en tu vida?",
      "¿Cuál ha sido tu experiencia más transformadora?",
      "¿Qué significa para ti el perdón?",
      "¿Qué te hace sentir amado/a?",
      "Si pudieras dar un consejo a todo el mundo, ¿cuál sería?",
      "¿Qué es lo que más te preocupa del futuro?",
      "¿Qué papel juega la gratitud en tu vida?",
      "Si pudieras revivir un día de tu vida, ¿cuál sería?",
      "¿Qué crees que nos hace humanos?",
      "¿Cuál es tu mayor desafío emocional actualmente?",
      "¿Qué significa para ti la conexión con otros?",
      "¿Cuál es la lección más importante que has aprendido del amor?",
      "¿Qué significa el éxito para ti?",
      "¿Qué acto de bondad reciente te hizo sentir bien?",
      "¿Qué te hace sentir en paz contigo mismo/a?",
      "¿Cuál es tu visión de una vida plena y significativa?",
      "Si pudieras cambiar algo de tu personalidad, ¿qué sería?",
      "¿Qué es lo más valiente que has hecho en tu vida?"
    ],
    retos: [
      "Cuenta una experiencia que haya cambiado tu vida",
      "Comparte tu mayor miedo y cómo lo enfrentas",
      "Habla de un momento en que superaste un gran desafío",
      "Explica qué significa la felicidad para ti",
      "Comparte un arrepentimiento y lo que aprendiste de él",
      "Habla de una persona que haya influido profundamente en tu vida",
      "Cuenta una lección que hayas aprendido de un fracaso",
      "Comparte algo que siempre has querido lograr y por qué",
      "Habla de un momento en que te sentiste verdaderamente orgulloso/a",
      "Describe tu mayor fortaleza y debilidad",
      "Comparte una experiencia que te haya hecho más fuerte",
      "Cuenta algo que te haya enseñado sobre la amistad",
      "Habla de un sueño que aún no has cumplido",
      "Comparte un momento que cambió tu perspectiva de la vida",
      "Explica qué significa para ti el amor verdadero",
      "Habla de un sacrificio que hayas hecho por alguien",
      "Cuenta algo que te haya hecho sentir vulnerable",
      "Comparte un momento que te haya enseñado gratitud",
      "Habla de un error del pasado que te haya enseñado mucho",
      "Cuenta algo que te haga sentir en paz contigo mismo/a",
      "Comparte un momento que te haya hecho replantear tu vida",
      "Habla de una decisión difícil y cómo la tomaste",
      "Cuenta una experiencia que te haya hecho más compasivo/a",
      "Comparte un recuerdo de la infancia que te marcó",
      "Habla de algo que siempre quisiste decir pero nunca dijiste",
      "Cuenta un momento en que ayudaste a alguien y te cambió",
      "Comparte una experiencia que te haya hecho más resiliente",
      "Habla de un logro que haya significado mucho para ti",
      "Cuenta algo que hayas superado y cómo lo lograste",
      "Comparte un momento que te haya enseñado sobre perdón",
      "Habla de una vez que enfrentaste un miedo",
      "Cuenta una experiencia que te haya enseñado paciencia",
      "Comparte algo que te haga sentir agradecido/a",
      "Habla de un momento que te haya inspirado profundamente",
      "Cuenta algo que hayas aprendido sobre ti mismo/a recientemente",
      "Comparte un momento que te haya hecho cambiar de opinión",
      "Habla de una vez que sentiste verdadera conexión con alguien",
      "Cuenta una experiencia que te haya enseñado humildad",
      "Comparte algo que te gustaría cambiar en tu vida y por qué",
      "Habla de un momento en que tomaste una decisión valiente",
      "Cuenta algo que hayas perdido y lo que aprendiste de ello",
      "Comparte un momento que te haya hecho reflexionar sobre la vida",
      "Habla de un momento que te haya enseñado a confiar en otros",
      "Cuenta algo que te haya enseñado sobre el amor",
      "Comparte un momento en que sentiste verdadera libertad",
      "Habla de una experiencia que te haya hecho más consciente de ti mismo/a",
      "Cuenta un momento que te haya enseñado a ser más empático/a",
      "Comparte un recuerdo que te haya marcado profundamente",
      "Habla de algo que hayas logrado superar y lo que significó",
      "Cuenta una experiencia que te haya hecho más agradecido/a",
      "Comparte un momento que te haya enseñado sobre la vida",
      "Habla de algo que siempre quisiste hacer pero nunca hiciste"
    ]
  }
};
